version: "3.9"

services:
    postgres:
        image: postgres:15.2
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: pgmq
            POSTGRES_DB: pgmq_db
            POSTGRES_HOST_AUTH_METHOD: trust

volumes:
    postgres-data:
