name: test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                  npm config set '@dumpstate:registry' 'https://npm.pkg.github.com'
                  npm config set '//npm.pkg.github.com/:_authToken' "${TOKEN}"
                  npm install
              env:
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
